version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: DockerfileApi
    restart: always
    image: api
    ports:
      - 5000:80
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro