version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: nodeapp
    ports:
      - 80:3000
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: nodeapi
    ports:
      - 4000:4000
