Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.define "wp" do |wp|
    wp.vm.network "private_network", ip: "192.168.33.10"
    wp.vm.provision "shell", inline: <<-SHELL
      apt-get clean
      apt update -y
    SHELL
  end
end