// <auto-generated />
using ApiMonedas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiMonedas.Migrations
{
    [DbContext(typeof(MonedasContext))]
    [Migration("20211215115935_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ApiMonedas.Models.Moneda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValorMaximo")
                        .HasColumnType("real");

                    b.Property<float>("ValorUltimo")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Monedas");
                });
#pragma warning restore 612, 618
        }
    }
}
